'use client'
import dynamic from 'next/dynamic';
import localFont from "next/font/local";
import "./globals.css";
// import { Provider } from "react-redux";
import { store } from '../Store';
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

 const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Provider = dynamic(() => import('react-redux').then((mod) => mod.Provider), { ssr: false });


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
         <Provider store={store} >

        {children}
         </Provider>
      </body>
    </html>
  );
}
